credit_taxonomy <-
  tibble::tibble('CRediT Taxonomy' = c("Conceptualization",
                                       "Data curation",
                                       "Formal analysis",
                                       "Funding acquisition",
                                       "Investigation",
                                       "Methodology",
                                       "Project administration",
                                       "Resources",
                                       "Software",
                                       "Supervision",
                                       "Validation",
                                       "Visualization",
                                       "Writing - original draft",
                                       "Writing - review & editing"),
                 url = c("http://credit.niso.org/contributor-roles/conceptualization/",
                         "http://credit.niso.org/contributor-roles/data-curation/",
                         "http://credit.niso.org/contributor-roles/formal-analysis/",
                         "http://credit.niso.org/contributor-roles/funding-acquisition/",
                         "http://credit.niso.org/contributor-roles/investigation/",
                         "http://credit.niso.org/contributor-roles/methodology/",
                         "http://credit.niso.org/contributor-roles/project-administration/",
                         "http://credit.niso.org/contributor-roles/resources/",
                         "http://credit.niso.org/contributor-roles/software/",
                         "http://credit.niso.org/contributor-roles/supervision/",
                         "http://credit.niso.org/contributor-roles/validation/",
                         "http://credit.niso.org/contributor-roles/visualization/",
                         "http://credit.niso.org/contributor-roles/writing-original-draft/",
                         "http://credit.niso.org/contributor-roles/writing-review-editing/"))

usethis::use_data(credit_taxonomy, overwrite = TRUE, internal = TRUE)
