credit_taxonomy <-
  tibble::tibble('CRediT Taxonomy' = c("Conceptualization",
                                       "Data Curation",
                                       "Formal Analysis",
                                       "Funding Acquisition",
                                       "Investigation",
                                       "Methodology",
                                       "Project Administration",
                                       "Resources",
                                       "Software",
                                       "Supervision",
                                       "Validation",
                                       "Visualization",
                                       "Writing - Original Draft Preparation",
                                       "Writing - Review & Editing"),
                 url = c("https://dictionary.casrai.org/Contributor_Roles/Conceptualization",
                         "https://dictionary.casrai.org/Contributor_Roles/Data_curation",
                         "https://dictionary.casrai.org/Contributor_Roles/Formal_analysis",
                         "https://dictionary.casrai.org/Contributor_Roles/Funding_acquisition",
                         "https://dictionary.casrai.org/Contributor_Roles/Investigation",
                         "https://dictionary.casrai.org/Contributor_Roles/Methodology",
                         "https://dictionary.casrai.org/Contributor_Roles/Project_administration",
                         "https://dictionary.casrai.org/Contributor_Roles/Resources",
                         "https://dictionary.casrai.org/Contributor_Roles/Software",
                         "https://dictionary.casrai.org/Contributor_Roles/Supervision",
                         "https://dictionary.casrai.org/Contributor_Roles/Validation",
                         "https://dictionary.casrai.org/Contributor_Roles/Visualization",
                         "https://dictionary.casrai.org/Contributor_Roles/Writing_original_draft",
                         "https://dictionary.casrai.org/Contributor_Roles/Writing_review_editing"))

usethis::use_data(credit_taxonomy, overwrite = TRUE, internal = TRUE)
