credit_taxonomy <-
  tibble::tibble('CRediT Taxonomy' = c("Conceptualization",
                                       "Data Curation",
                                       "Formal Analysis",
                                       "Funding Acquisition",
                                       "Investigation",
                                       "Methodology",
                                       "Project Administration",
                                       "Resources",
                                       "Software",
                                       "Supervision",
                                       "Validation",
                                       "Visualization",
                                       "Writing - Original Draft Preparation",
                                       "Writing - Review & Editing"),
                 url = c("http://credit.niso.org/contributor-roles/conceptualization/",
                         "http://credit.niso.org/contributor-roles/data-curation/",
                         "http://credit.niso.org/contributor-roles/formal-analysis/",
                         "http://credit.niso.org/contributor-roles/funding-acquisition/",
                         "http://credit.niso.org/contributor-roles/investigation/",
                         "http://credit.niso.org/contributor-roles/methodology/",
                         "http://credit.niso.org/contributor-roles/project-administration/",
                         "http://credit.niso.org/contributor-roles/resources/",
                         "http://credit.niso.org/contributor-roles/software/",
                         "http://credit.niso.org/contributor-roles/supervision/",
                         "http://credit.niso.org/contributor-roles/validation/",
                         "http://credit.niso.org/contributor-roles/visualization/",
                         "http://credit.niso.org/contributor-roles/writing-original-draft/",
                         "http://credit.niso.org/contributor-roles/writing-review-editing/"))

usethis::use_data(credit_taxonomy, overwrite = TRUE, internal = TRUE)
